apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-serving
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model-serving
  template:
    metadata:
      labels:
        app: mlflow-model-serving
    spec:
      containers:
      - name: mlflow-model-container
        image: ghcr.io/mlflow/mlflow:v2.19.0
        command: ["mlflow", "models", "serve"]
        args:
          - "-m"
          - "models:/{{MODEL_NAME}}/{{MODEL_VERSION}}"
          - "-h"
          - "0.0.0.0"
          - "-p"
          - "5001"
          - "--no-conda"
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local:80"

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
  namespace: airflow
spec:
  selector:
    app: mlflow-model-serving
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 31080
    name: http-mlflow
  type: NodePort